/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Registration = IDL.Record({
  'id' : IDL.Text,
  'teamName' : IDL.Text,
  'proofOfPaymentUrl' : IDL.Opt(ExternalBlob),
  'whatsappLink' : IDL.Text,
  'playerPhotoUrl' : IDL.Opt(ExternalBlob),
  'referredBy' : IDL.Opt(IDL.Text),
  'paymentScreenshotUrl' : IDL.Opt(ExternalBlob),
  'response' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'registeredAt' : IDL.Int,
  'teamLogoUrl' : IDL.Opt(ExternalBlob),
});
export const ShortUrl = IDL.Record({
  'clicks' : IDL.Nat,
  'originalUrl' : IDL.Text,
  'code' : IDL.Text,
  'createdAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createRegistration' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Text),
      ],
      [Registration],
      [],
    ),
  'createShortUrl' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(ShortUrl)], []),
  'deleteAllRegistrations' : IDL.Func([], [IDL.Nat], []),
  'deleteRegistration' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteShortUrl' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getRegistration' : IDL.Func([IDL.Text], [IDL.Opt(Registration)], ['query']),
  'getRegistrationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'listRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'listShortUrls' : IDL.Func([], [IDL.Vec(ShortUrl)], ['query']),
  'resolveShortUrl' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Registration = IDL.Record({
    'id' : IDL.Text,
    'teamName' : IDL.Text,
    'proofOfPaymentUrl' : IDL.Opt(ExternalBlob),
    'whatsappLink' : IDL.Text,
    'playerPhotoUrl' : IDL.Opt(ExternalBlob),
    'referredBy' : IDL.Opt(IDL.Text),
    'paymentScreenshotUrl' : IDL.Opt(ExternalBlob),
    'response' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'registeredAt' : IDL.Int,
    'teamLogoUrl' : IDL.Opt(ExternalBlob),
  });
  const ShortUrl = IDL.Record({
    'clicks' : IDL.Nat,
    'originalUrl' : IDL.Text,
    'code' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createRegistration' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Text),
        ],
        [Registration],
        [],
      ),
    'createShortUrl' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(ShortUrl)], []),
    'deleteAllRegistrations' : IDL.Func([], [IDL.Nat], []),
    'deleteRegistration' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteShortUrl' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getRegistration' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Registration)],
        ['query'],
      ),
    'getRegistrationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'listRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'listShortUrls' : IDL.Func([], [IDL.Vec(ShortUrl)], ['query']),
    'resolveShortUrl' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  });
};

export const init = ({ IDL }) => { return []; };